omegga:
  webui: true
  port: 8080
  https: true
  # Increase Node.js heap memory limit to handle large worlds
  # brs-js has limitations with "numbers potentially larger than Javascript can handle"
  node_args: 
    - "--max-old-space-size=65536"
    - "--max-semi-space-size=2048"
    - "--max-new-space-size=4096"
    - "--optimize-for-size"
    - "--gc-interval=100"
    - "--expose-gc"
    - "--max-http-header-size=32768"
    - "--max-buffer-size=16777216"
    - "--stack-size=8192"
server:
  port: 7777
  map: Plate
